### ISSUE TITLE
Support React v18

### ISSUE THREAD

**Issue by smwa** [Adonis-Stavridis/caroumesh#1]
I have been using the library and it's been very helpful! I went to upgrade my project to React v18 and found that this is set to v17. Could we have the React version bumped? I'm happy to do it and make a PR, if you'd prefer

**Comment by Adonis-Stavridis** [comment]
Hello! Thank you for your suggestion. I've been quite busy for a while.
I am planning on reworking and updating this project, hopefully until the end of August.
I will let you know when I manage to have something functionnal.

**Comment by Adonis-Stavridis** [comment]
👋 Hello! So I'm back, after a while... sorry for the long wait. I've just released a new version of the component, which includes a bump to React v18, and a lot more: https://github.com/Adonis-Stavridis/caroumesh/releases/tag/v1.2.2
Hope that this fixes your problems with this component. 👍
